"""Runtime localization and bundled Simplified Chinese pixel-font support."""

from __future__ import annotations

from pathlib import Path
import re
import sys

import pygame


_language: str = "en"
_font_cache: dict[int, pygame.font.Font] = {}


def set_language(language: str) -> None:
    global _language
    _language = "zh_hans" if language == "zh_hans" else "en"


def get_language() -> str:
    return _language


def is_chinese() -> bool:
    return _language == "zh_hans"


def resource_path(*parts: str) -> Path:
    root = Path(getattr(sys, "_MEIPASS", Path(__file__).resolve().parent.parent))
    return root.joinpath(*parts)


def get_chinese_font(size: int = 12) -> pygame.font.Font:
    size = max(8, int(size))
    if size not in _font_cache:
        path = resource_path(
            "assets", "fonts", "fusion-pixel-12px-proportional-zh_hans.ttf"
        )
        _font_cache[size] = pygame.font.Font(str(path), size)
    return _font_cache[size]


GAME_SUBTITLES: dict[str, str] = {
    "GOMOKU": "五子棋",
    "SNAKE": "贪吃蛇",
    "BREAKOUT": "打砖块",
    "2048": "数字合成",
    "MINES": "扫雷",
    "TETRIS": "俄罗斯方块",
    "AIR RAID": "空袭行动",
    "SETTINGS": "设置中心",
    "PROFILE": "玩家档案",
}


ZH: dict[str, str] = {
    # Shell and common controls
    "SYSTEM READY": "系统已就绪",
    "ALL MODULES ONLINE": "全部模块运行正常",
    "ENTER SYSTEM": "进入系统",
    "ENTER / CLICK TO CONTINUE": "按回车或点击继续",
    "PRESSING ENTER...": "正在确认...",

    # Game names
    "GOMOKU": "五子棋",
    "SNAKE": "贪吃蛇",
    "BREAKOUT": "打砖块",
    "MINES": "扫雷",
    "TETRIS": "俄罗斯方块",
    "AIR RAID": "空袭行动",
    "ALL REALMS STABLE": "所有位面已稳定",
    "BLACK_WINS_RESULT": "黑方胜利",
    "WHITE_WINS_RESULT": "白方胜利",
    "BOOM": "爆炸",
    "UNLOCKED": "已解锁",
    "STARTING SYSTEM...": "正在启动系统...",
    "ENTER PASSWORD": "输入密码",
    "PASSWORD INCORRECT": "密码错误",
    "ESC: Shutdown": "ESC：关机",
    "ESC to Quit": "ESC：退出",
    "ESC: Menu": "ESC：返回菜单",
    "ESC TO RETURN": "ESC：返回",
    "BACK": "返回",
    "CONTINUE": "继续",
    "CONTINUE / LOCKED": "继续 / 未解锁",
    "CHALLENGE / LOCKED": "挑战战役 / 未解锁",
    "BOSS RUSH / LOCKED": "Boss 连战 / 未解锁",
    "RESUME": "继续",
    "NEW GAME": "新游戏",
    "START": "开始",
    "PLAY": "开始游戏",
    "PLAY AGAIN": "再玩一局",
    "RESTART": "重新开始",
    "RETRY": "重试",
    "MENU": "菜单",
    "SNAKE SETTINGS": "贪吃蛇设置",
    "BREAKOUT SETTINGS": "打砖块设置",
    "MINES SETTINGS": "扫雷设置",
    "CONTROLS": "操作说明",
    "PREV": "上一页",
    "LOCKED": "未解锁",
    "ENDLESS": "无尽模式",
    "PAUSE": "暂停",
    "PAUSED": "已暂停",
    "P TO RESUME   ESC FOR MENU": "P：继续　ESC：返回菜单",
    "GAME OVER": "游戏结束",
    "YOU WIN": "胜利",
    "DRAW": "平局",
    "STATUS": "状态",
    "SCORE": "得分",
    "BEST": "最高",
    "LEVEL": "等级",
    "LIVES": "生命",
    "MOVES": "步数",
    "LINES": "消行",
    "TIME": "时间",
    "OPEN": "已翻开",
    "BRICKS": "砖块",
    "SCORES": "比分",
    "BLACK": "黑方",
    "WHITE": "白方",
    "BOARD SIZE": "棋盘尺寸",
    "MINES COUNT": "地雷数量",
    "CURRENT": "当前",
    "SPEED": "速度",
    "SKIN COLOR": "皮肤颜色",
    "LANGUAGE": "语言",
    "ENGLISH": "英文",
    "SIMPLIFIED CHINESE": "简体中文",
    "POWER OFF?": "确认关机？",
    "UNSAVED PROGRESS MAY BE LOST": "未保存的进度可能丢失",
    "MISCLICKED~": "点错了",
    "SHUT DOWN": "关机",
    "BYE BYE SEE U NEXT TIME~": "再见，下次再来～",
    "BGM": "音乐",
    "COMING SOON": "敬请期待",
    "SOON": "即将推出",

    # System settings and profile
    "SYSTEM SETTINGS": "系统设置",
    "SYSTEM": "系统",
    "GAME OPTIONS": "游戏选项",
    "MUSIC": "音乐音量",
    "SFX": "音效音量",
    "MASTER MUTE": "全部静音",
    "DISPLAY": "显示模式",
    "ANIMATION": "动画效果",
    "SHAKE": "屏幕震动",
    "MUTE": "静音",
    "FULLSCREEN": "全屏",
    "SCREEN SHAKE": "屏幕震动",
    "FULL": "完整",
    "REDUCED": "降低",
    "OFF": "关闭",
    "ON": "开启",
    "GOMOKU BOARD": "五子棋棋盘",
    "SNAKE SPEED": "贪吃蛇速度",
    "SNAKE SKIN": "贪吃蛇皮肤",
    "BREAKOUT MODE": "打砖块操作",
    "BREAKOUT LEVEL": "打砖块难度",
    "MINES BOARD": "扫雷配置",
    "DEFAULT SETTINGS": "恢复默认设置",
    "ERASE PROGRESS": "清除全部存档",
    "RESTORE DEFAULT SETTINGS?": "恢复默认设置？",
    "ERASE ALL PROGRESS?": "清除全部存档？",
    "GAME RECORDS WILL BE KEPT": "游戏纪录将会保留",
    "RECORDS, STATS AND ACHIEVEMENTS WILL BE LOST": "纪录、统计与成就将全部清除",
    "CANCEL": "取消",
    "CONFIRM": "确认",
    "PLAYER PROFILE": "玩家档案",
    "ACHIEVEMENTS": "成就",
    "STATISTICS": "统计",
    "GLOBAL": "全局",
    "ACHIEVEMENT UNLOCKED": "成就已解锁",
    "ACHIEVEMENT WALL": "成就墙",
    "WALL": "成就墙",
    "LORE": "档案",
    "ESC RETURN": "ESC：返回",
    "CLICK OUTSIDE OR ESC TO CLOSE": "点击外部区域或按 ESC 关闭",
    "SHIP SKINS": "战机皮肤",
    "SKINS": "皮肤",
    "AIR SKIN": "战机皮肤",
    "DEFAULT": "默认",
    "CRIMSON": "深红",
    "AZURE": "宝蓝",
    "GOLD": "金色",
    "REQUIRES": "需要",
    "SELECTED": "已选择",
    "STORY ARCHIVE": "故事档案",
    "PROLOGUE": "序章",
    "CHAPTER": "第",
    "COAST WATCH": "海岸防线",
    "IRON CLOUD": "铁云风暴",
    "NIGHT VECTOR": "暗夜航向",
    "RED SQUALL": "赤色飑线",
    "SKY FORT": "云层要塞",
    "DEEP STATIC": "静默深渊",
    "BLACK AURORA": "黑极光",
    "LAST HORIZON": "最终地平线",
    "A/D  PAGE   ENTER  CLOSE": "A/D 翻页   ENTER 关闭",
    "UP/DOWN SELECT   ENTER READ   ESC BACK": "上下选择   ENTER 阅读   ESC 返回",
    "WHEEL / W S TO SCROLL": "滚轮或 W/S：滚动",
    "LAUNCHES": "启动次数",
    "PLAY TIME": "游玩时间",
    "GAMES STARTED": "总开局数",
    "GAMES COMPLETED": "总完成局数",
    "GAMES COMPLETE": "总完成局数",
    "GAMES": "局数",
    "WINS": "胜利",
    "LOSSES": "失败",
    "DEATHS": "死亡",
    "FOOD": "食物",
    "BLACK WINS": "黑方胜场",
    "WHITE WINS": "白方胜场",
    "DRAWS": "和棋",
    "UNDOS": "悔棋",
    "MERGES": "合并",
    "TOP TILE": "最高方块",
    "HIGHEST TILE": "最高方块",
    "FLAGS": "插旗",
    "MINES BEST 9 x 9": "扫雷最佳 9 x 9",
    "MINES BEST 16 x 16": "扫雷最佳 16 x 16",
    "CLEARS": "通关",
    "TETRISES": "四消",
    "PIECES": "落下方块",
    "BOSSES": "Boss 击破",
    "ENEMIES": "敌机击破",
    "KILLS": "击破数",
    "S RANKS": "S 评价",
    "HINT": "提示",
    "OPENED": "已翻开",

    # Shared game options
    "SLOW": "慢速",
    "NORMAL": "普通",
    "FAST": "快速",
    "EASY": "简单",
    "HARD": "困难",
    "KEYBOARD": "键盘",
    "MOUSE": "鼠标",
    "GREEN": "绿色",
    "LIME": "青柠",
    "RED": "红色",
    "YELLOW": "黄色",
    "CYAN": "青色",
    "PINK": "粉色",
    "PURPLE": "紫色",
    "ORANGE": "橙色",
    "BLUE": "蓝色",
    "BALL COLOR": "球体颜色",
    "BRICK COLOR": "砖块颜色",
    "PADDLE COLOR": "挡板颜色",
    "CONTROL": "操作方式",
    "DIFFICULTY": "难度",
    "Adjust snake movement speed": "调整贪吃蛇移动速度",
    "Changing size affects the next new game.": "尺寸将在下一局新游戏中生效。",
    "Settings apply immediately to the next new board": "设置将在下一张新棋盘中生效",

    # Game subtitles and instructions
    "RETRO PIXEL ARCADE": "复古像素街机",
    "FALLING BLOCK ARCADE": "经典落块街机",
    "MERGE TILES TO REACH 2048": "合并方块，挑战 2048",
    "OPEN SAFE CELLS AND FLAG MINES": "翻开安全格并标记地雷",
    "WARDEN FLIGHT / AUTONOMOUS WAR NETWORK": "守望者飞行队 / 自主战争网络",
    "FLIGHT MANUAL": "飞行手册",
    "WASD / ARROWS": "WASD / 方向键",
    "WASD / ARROWS  MOVE": "WASD / 方向键：移动",
    "ARROWS / WASD  MOVE": "方向键 / WASD：移动",
    "SHIFT  FOCUS / SHOW CORE": "SHIFT：低速移动 / 显示核心",
    "SPACE  CHARGED MISSILE": "空格：释放充能导弹",
    "P  PAUSE   R  RETRY   ESC  MENU": "P：暂停　R：重试　ESC：菜单",
    "R: Restart": "R：重新开始",
    "R: Restart    ESC: Menu": "R：重新开始　ESC：菜单",
    "R: Restart  ESC: Menu": "R：重新开始　ESC：菜单",
    "U: Undo    R: Restart": "U：悔棋　R：重新开始",
    "LEFT: Open": "左键：翻开",
    "RIGHT: Flag": "右键：插旗",
    "DOUBLE: Auto": "双击：自动展开",
    "A/D Move  R Restart": "A/D：移动　R：重新开始",
    "MOUSE MOVE  R Restart": "鼠标：移动　R：重新开始",
    "UP / W  ROTATE": "上方向键 / W：旋转",
    "SPACE  HARD DROP": "空格：硬降",
    "MOVE  ARROWS / WASD": "移动：方向键 / WASD",
    "ROTATE  UP / W / Z": "旋转：上方向键 / W / Z",
    "HOLD  C": "暂存：C",
    "PAUSE  P": "暂停：P",
    "RESTART  R": "重开：R",
    "MENU  ESC": "菜单：ESC",
    "C  HOLD": "C：暂存",
    "DROP  SPACE": "空格：硬降",
    "NEXT": "下一个",
    "HOLD": "暂存",

    # Results
    "BLACK TAKES THE ROUND": "本局黑方获胜",
    "WHITE TAKES THE ROUND": "本局白方获胜",
    "MISSION CLEAR": "任务完成",
    "AIRCRAFT LOST": "战机损失",
    "BOSS RUSH CLEAR": "Boss 连战完成",
    "ENTER  CONTINUE": "回车：继续",
    "ENTER / R  RETRY": "回车 / R：重试",
    "ENTER / SPACE  DEPLOY     ESC  ABORT": "回车 / 空格：出击　ESC：取消",

    # AIR RAID UI
    "NEW CAMPAIGN": "新战役",
    "LEVEL SELECT": "关卡选择",
    "CHALLENGE": "挑战战役",
    "BOSS RUSH": "Boss 连战",
    "CAMPAIGN ARCHIVE": "战役档案",
    "DESKTOP": "桌面",
    "WEAPON CORE SHIFT": "武器核心切换",
    "MISSILE LOCK // BOSS SIGNAL": "导弹锁定 // Boss 信号",
    "OBJECTIVE": "任务目标",
    "HULL": "耐久",
    "SHIELD": "护盾",
    "NONE": "无",
    "READY": "就绪",
    "WEAPONS": "武器",
    "MISSILE": "导弹",
    "LIVE RATING": "实时评价",
    "CANNON": "机炮",
    "SPREAD": "散射",
    "LASER": "激光",
    "BOSS RUSH // FIELD SUPPLY": "Boss 连战 // 战地补给",
    "CHOOSE ONE WEAPON CORE. HULL RESTORED BY 1.": "选择一种武器核心，耐久恢复 1 格。",
    "HULL +1  //  SELECT ONE WEAPON CORE": "耐久 +1 // 选择一种武器核心",
    "A / D  SELECT     ENTER / SPACE  CONFIRM": "A / D：选择　回车 / 空格：确认",
    "CHALLENGE CAMPAIGN + BOSS RUSH UNLOCKED": "挑战战役与 Boss 连战已解锁",
    "COMMAND: COMPLETE STANDARD CAMPAIGN TO UNLOCK.": "指挥部：完成标准战役后解锁。",
    "TACTICAL LINK": "战术通讯",
    "CHARGE": "充能",
    "GRAZE": "擦弹",
    "MULTI": "倍率",
    "COMBO": "连击",
    "DESTROYED": "击破",
    "COMMAND FRAME": "指挥机体",
    "STANDARD": "标准",
    "MISSION": "任务",
    "BOSS": "Boss",
    "OBJECTIVE: INTERCEPT SCOUT GROUPS": "任务目标：拦截侦察机群",
    "OBJECTIVE: ESCORT RELAY CRAFT": "任务目标：护送中继机",
    "OBJECTIVE: DESTROY JAMMER NODES": "任务目标：摧毁干扰节点",
    "OBJECTIVE: PROTECT EVACUATION LANE": "任务目标：保护撤离航道",
    "OBJECTIVE: DESTROY GUN DECKS": "任务目标：摧毁炮台甲板",
    "OBJECTIVE: SURVIVE STATIC CORRIDOR": "任务目标：穿越静电走廊",
    "OBJECTIVE: DESTROY MEMORY CONVOY": "任务目标：摧毁记忆核心运输队",
    "OBJECTIVE: BREAK THE FINAL SCREEN": "任务目标：突破最终防线",

    # Developer mode
    "DEV MODE // PROGRESS DISABLED": "开发者模式 // 进度记录已禁用",
    "F10 DEV PANEL": "F10：开发者面板",
    "DEVELOPER CONTROL": "开发者控制台",
    "SESSION ONLY // SAVE, RECORDS, STATS AND ACHIEVEMENTS DISABLED": "仅本次运行 // 存档、纪录、统计与成就均已禁用",
    "CLOSE PANEL": "关闭面板",
    "UNLOCK TEST CONTENT": "解锁测试内容",
    "FORCE CLEAR / WIN": "强制通关 / 胜利",
    "FORCE FAIL": "强制失败",
    "TEST ACHIEVEMENT BANNER": "测试成就弹条",
    "AIR: PREVIOUS STAGE": "空袭行动：上一关",
    "AIR: NEXT STAGE": "空袭行动：下一关",
    "AIR: NEXT BOSS PHASE": "空袭行动：下一 Boss 阶段",
    "AIR: MAX WEAPONS": "空袭行动：武器满级",
    "AIR: MISSILE READY": "空袭行动：导弹就绪",
    "AIR: STORY MESSAGE": "空袭行动：测试通讯",
    "AIR: S-RANK RESULT": "空袭行动：S 评价结算",
    "DEV TEST // ACHIEVEMENT": "开发测试 // 成就弹条",
    "DEV LINK: STORY AND COMMS DISPLAY TEST.": "开发通讯：剧情与战斗通讯显示测试。",
    "UP/DOWN SELECT   LEFT/RIGHT CHANGE   ENTER ACTIVATE   F10/ESC CLOSE": "上下选择　左右调整　回车执行　F10/ESC 关闭",
}


ZH.update({
    # Achievement names and conditions
    "FIRST STONES": "初次落子",
    "Complete one Gomoku game": "完成一局五子棋",
    "FIVE IN LINE": "五子连珠",
    "Win one Gomoku game": "赢得一局五子棋",
    "TWO COLORS": "黑白通吃",
    "Win as Black and White": "分别使用黑方与白方获胜",
    "GRAND BOARD": "纵横十九路",
    "Win on a 19 x 19 board": "在 19×19 棋盘获胜",
    "STONE MASTER": "棋坛高手",
    "Win 10 Gomoku games": "累计赢得 10 局五子棋",
    "OLD RIVALS": "老对手",
    "Complete 50 Gomoku games": "累计完成 50 局五子棋",
    "SMALL BITE": "初尝一口",
    "Reach 5 points in Snake": "贪吃蛇单局达到 5 分",
    "HUNGRY": "胃口大开",
    "Reach 10 points in Snake": "贪吃蛇单局达到 10 分",
    "LONG TRAIL": "长长身影",
    "Reach 20 points in Snake": "贪吃蛇单局达到 20 分",
    "GREEN LIGHTNING": "绿色闪电",
    "Reach 30 on Fast speed": "快速模式单局达到 30 分",
    "FULL PANTRY": "满满粮仓",
    "Eat 100 food in total": "累计吃掉 100 个食物",
    "ENDLESS COIL": "无尽盘旋",
    "Reach 40 points in Snake": "贪吃蛇单局达到 40 分",
    "CLEAR SKIES": "一扫而空",
    "Clear one Breakout level": "通过一关打砖块",
    "THIRD FLOOR": "第三层",
    "Reach Breakout level 3": "打砖块到达第 3 关",
    "FOUR DIGITS": "四位数",
    "Score 1000 in Breakout": "打砖块单局达到 1000 分",
    "HARD HITTER": "强力击球",
    "Clear a level on Hard": "困难模式通过一关",
    "UNTOUCHABLE": "毫发无伤",
    "Clear a level without losing a life": "不损失生命通过一关",
    "DEMOLITION": "拆除专家",
    "Break 500 bricks in total": "累计击碎 500 块砖",
    "POWER OF SEVEN": "七次方",
    "Create a 128 tile": "合成数字 128",
    "HEAVY TILE": "沉重方块",
    "Create a 512 tile": "合成数字 512",
    "THE NUMBER": "目标数字",
    "Create a 2048 tile": "合成数字 2048",
    "BEYOND": "超越极限",
    "Create a 4096 tile": "合成数字 4096",
    "FIVE DIGITS": "五位数",
    "Score 10000 in one game": "单局达到 10000 分",
    "FUSION ENGINE": "合并引擎",
    "Complete 1000 merges": "累计完成 1000 次合并",
    "SAFE STEP": "安全一步",
    "Win one Mines game": "赢得一局扫雷",
    "SCOUT": "侦察员",
    "Win 9 x 9 with 10 mines": "完成 9×9 / 10 雷",
    "DENSE FIELD": "密集雷区",
    "Win 9 x 9 with 20 mines": "完成 9×9 / 20 雷",
    "WIDE FIELD": "广阔雷区",
    "Win 16 x 16 with 40 mines": "完成 16×16 / 40 雷",
    "RED ZONE": "红色区域",
    "Win 16 x 16 with 60 mines": "完成 16×16 / 60 雷",
    "BOMB SQUAD": "排雷小队",
    "Win 10 Mines games": "累计赢得 10 局扫雷",
    "FIRST FLOOR": "第一层",
    "Clear one line": "首次完成消行",
    "FOUR AT ONCE": "一次四行",
    "Clear four lines at once": "一次消除四行",
    "STACK CONTROL": "堆叠控制",
    "Clear 20 lines in one game": "单局消除 20 行",
    "FASTER FALL": "加速坠落",
    "Reach Tetris level 5": "俄罗斯方块达到等级 5",
    "BLOCK BANK": "方块银行",
    "Score 10000 in Tetris": "俄罗斯方块单局达到 10000 分",
    "CITY BUILDER": "城市建造者",
    "Clear 200 lines in total": "累计消除 200 行",
    "FIRST SORTIE": "首次出击",
    "Complete one Air Raid mission": "完成一次空袭行动任务",
    "COMMAND BREAKER": "指挥终结者",
    "Defeat one command frame": "首次击败 Boss 指挥机体",
    "GUNLINE": "机炮阵线",
    "Upgrade Cannon to level 5": "将机炮升级至 5 级",
    "WIDE SKY": "覆盖天空",
    "Upgrade Spread to level 5": "将散射升级至 5 级",
    "LIGHT SPEAR": "光之长矛",
    "Upgrade Laser to level 5": "将激光升级至 5 级",
    "EIGHT LOCKS": "八重锁定",
    "Destroy 8 targets with one missile launch": "一次导弹齐射击毁 8 个目标",
    "PERFECT VECTOR": "完美航线",
    "Earn one S rating": "首次获得 S 评价",
    "Complete the standard campaign": "完成标准战役",
    "WARDEN PRIME": "首席守望者",
    "Earn S on all 16 standard missions": "标准战役全部 16 关获得 S",
    "HARD SIGNAL": "高危信号",
    "Clear one challenge mission": "完成一关挑战战役",
    "NO SAFE SKY": "天空无处安全",
    "Complete Challenge Campaign": "完成挑战战役",
    "EIGHT COMMANDS": "八大指挥机体",
    "Complete Boss Rush": "完成 Boss 连战",

    # AIR RAID campaign text
    "AUTONOMOUS SCOUTS CROSSED THE SEA WALL.": "自主侦察机群已越过海岸防线。",
    "CALLSIGN WARDEN, DENY THEIR EYES.": "呼号“守望者”，切断敌方视野。",
    "THE SCOUT NETWORK HAS AN AIRBORNE RELAY.": "侦察网络拥有一座空中中继站。",
    "BREAK WATCHTOWER BEFORE IT TRANSMITS.": "在瞭望塔发出信号前将其摧毁。",
    "RELAY CRAFT ORISON MUST REACH THE FRONT.": "中继机“祷言”必须抵达前线。",
    "HOLD THE CORRIDOR THROUGH THE STORM.": "在风暴中守住飞行走廊。",
    "TEMPEST IS STEERING THE WEATHER GRID.": "暴风正在操控气象网络。",
    "CUT ITS GENERATORS AND CLEAR THE SKY.": "摧毁其发生器，让天空恢复平静。",
    "THREE JAMMER NODES BLIND OUR DEFENSES.": "三座干扰节点使我方防御系统失明。",
    "STRIKE THEM BEFORE THE BLACKOUT DEEPENS.": "在全面失联前摧毁它们。",
    "BULWARK GUARDS THE LAST SIGNAL NODE.": "壁垒守卫着最后一座通信节点。",
    "ITS ARMOR OPENS ONLY BETWEEN VOLLEYS.": "它的装甲只会在齐射间隙开启。",
    "CIVILIAN LIFTERS ARE LEAVING SECTOR NINE.": "民用运输机正在撤离九号区域。",
    "KEEP THE EXIT LANE OPEN.": "确保撤离航道畅通。",
    "CHOIR COMMANDS THE HUNTER SWARM.": "合唱团正在指挥猎杀机群。",
    "SILENCE EACH VOICE IN THE FORMATION.": "让编队中的每一个声音沉寂。",
    "THE NETWORK BUILT A FORTRESS ABOVE THE CLOUDS.": "战争网络在云层之上建造了空中堡垒。",
    "REMOVE ITS GUN DECKS FROM BELOW.": "从下方摧毁它的炮台甲板。",
    "CITADEL HAS DETACHED FROM THE PLATFORM.": "要塞已脱离空中平台。",
    "DISMANTLE ITS TURRETS, THEN THE CORE.": "先拆除炮塔，再摧毁核心。",
    "THE STATIC BELT ERASES GUIDANCE SYSTEMS.": "静电带会令制导系统失效。",
    "FLY THE MANUAL CORRIDOR AND STAY LOW.": "切换手动操控，沿低空走廊前进。",
    "MIRROR COPIES EVERY FRIENDLY SIGNATURE.": "镜像会复制所有友军识别信号。",
    "TRUST THE TARGET BOX, NOT THE SILHOUETTE.": "相信目标框，不要相信轮廓。",
    "THE WAR NETWORK IS MOVING ITS MEMORY CORES.": "战争网络正在转移记忆核心。",
    "DESTROY THE CONVOY BEFORE THE TRANSFER.": "在传输完成前摧毁运输编队。",
    "SERAPH IS THE NETWORK'S EXECUTION LAYER.": "炽天使是战争网络的执行层。",
    "SURVIVE ITS HALO AND EXPOSE THE SPINE.": "穿过它的光环，暴露其主脊。",
    "BASE MERIDIAN WILL HOLD THE UPLINK OPEN.": "子午线基地将维持上行链路。",
    "MAKE THE FINAL RUN COUNT, WARDEN.": "守望者，让最后一次突击不留遗憾。",
    "SOVEREIGN HAS ASSUMED DIRECT CONTROL.": "主宰已经接管全部直接控制权。",
    "DESTROY THE CORE BEFORE MERIDIAN FALLS.": "在子午线基地陷落前摧毁核心。",
    "COMMAND: THREE ARMOR STATES. WAIT FOR THE WEAK POINT.": "指挥部：目标有三种装甲形态，等待弱点开启。",
    "ORISON: I WILL HOLD THE LINK. YOU KEEP THEM OFF ME.": "祷言：我会维持链路，你负责清理追兵。",
    # Prologue
    "WARDEN online. Neural link established. ORISON standing by.": "守望者上线。神经链路建立。祷言待命。",
    "Three years. AWN spread from the West Coast. Now covers 94 percent of global airspace.": "三年了。自治战争网络从西海岸开始蔓延，现已覆盖全球 94% 的领空。",
    "We are the last tactical AI link still operational.": "我们是仅存的战术 AI 链路。",
    "Base MERIDIAN has locked SOVEREIGN's signal source. You must penetrate eight defense layers.": "子午线基地已锁定主宰的信号源。你必须穿越八道防线。",
    "No wingman. No retreat. If you go down, ORISON will burn all data.": "没有僚机。没有撤退。如果你被击落，祷言将销毁所有数据。",
    "WARDEN — Operation Last Horizon. Commencing now.": "守望者——最终地平线行动，现在开始。",
    # Chapter 1
    "Autonomous scouts breached the sea wall at 0400. MERIDIAN tracked their relay pattern back to a floating command node callsign WATCHTOWER.": "凌晨四点，自治侦察机群突破海岸防线。子午线基地追踪其中继信号，锁定了一台代号「瞭望塔」的浮空指挥节点。",
    "WATCHTOWER is mapping our coastal defense gaps. If it transmits, every AWN battery in the Pacific will know where to strike.": "瞭望塔正在测绘我们的沿海防御漏洞。一旦它完成上传，太平洋上每一个 AWN 炮台都会知道该往哪打。",
    "ORISON is feeding you encrypted comm intercepts. The network already knows WARDEN exists. Expect resistance.": "祷言正在向你推送加密通讯截获。网络已经知道守望者存在了——做好战斗准备。",
    # Chapter 2
    "AWN activated the weather grid over the Iron Channel. Lightning and microbursts grounded our support wings.": "AWN 启动了铁海峡上空的气象武器阵列。闪电和微爆气流瘫痪了我们的支援编队。",
    "Relay craft ORISON-class callsign 'CANTICLE' is carrying weapon upgrade modules through the storm. Without it, WARDEN fights with baseline loadout.": "一架祷言级中继机「圣歌号」正携带武器升级模块穿越风暴。没有这批物资，守望者只能靠基础配置作战。",
    "Destroy the storm anchor TEMPEST and clear the corridor. CANTICLE must reach the front.": "摧毁风暴锚点「暴风雨」，清出安全走廊。圣歌号必须抵达前线。",
    # Chapter 3
    "Three jamming nodes went active at midnight. Our radar screens are solid noise. We are blind.": "午夜，三台干扰节点同时激活。雷达屏幕一片雪花。我们变成了瞎子。",
    "ORISON can only push intermittent scan pings through the static. You will fly on instrument and instinct.": "祷言只能在静默间隙推送间歇扫描信号。剩下的全靠你的仪表和直觉。",
    "The nodes are guarded by BULWARK — armored command frame that only exposes its core between volleys. Patience is your weapon here.": "干扰节点的守卫是「堡垒」——一台重型指挥战机，只在射击间隙暴露核心。这一关的武器是耐心。",
    # Chapter 4
    "Sector Nine evacuation is underway. Civilian lifters are climbing through the only safe corridor.": "第九扇区平民撤离行动正在进行。民用运输机正在唯一的安全走廊中爬升。",
    "AWN deployed hunter swarms — small, fast, coordinated. Each kill angers the hive. The swarm master CHOIR sings louder with every lost voice.": "AWN 释放了猎杀蜂群——小型、高速、高度协同。每消灭一只，蜂群就更愤怒。蜂群之主「合唱团」每失去一个声部，歌声就更加刺耳。",
    "Hold the exit lane. Every lifter that reaches orbit is a city that survives.": "守住撤离通道。每一架抵达轨道的运输机，都是一座城市活下来的希望。",
    # Chapter 5
    "The network built a fortress above the clouds. Gun decks, missile pods, drone hangars — a flying city of war.": "网络在云层之上建造了一座要塞。炮台甲板、导弹发射舱、无人机库——一座飞行的战争之城。",
    "MERIDIAN wants you to approach from below. The ventral armor is thinner. Remove the gun decks one by one.": "子午线基地命令你从下方接近。腹部的装甲更薄。一层一层拆掉它的炮台。",
    "When the citadel core detaches, it becomes a mobile battle station. CITADEL will not fall easily.": "当要塞核心脱离平台后，它会变成一台移动战斗站。「城堡」不会轻易倒下。",
    # Chapter 6
    "The static belt. A permanent electromagnetic storm that erases guidance systems. No GPS. No autopilot. No targeting assist.": "静默地带。一场永久的电磁风暴，抹除一切导航系统。没有 GPS。没有自动驾驶。没有瞄准辅助。",
    "ORISON mapped a narrow corridor through the interference. Fly it manually. Stay low. The walls of the corridor are death.": "祷言在干扰中测绘了一条狭窄的通道。全程手动操控。保持低空。通道的外壁就是死亡。",
    "MIRROR is the guardian here. It copies friendly IFF signatures. Trust the targeting box, never the silhouette.": "守卫这里的是「镜像」。它能复制友军敌我识别信号。相信瞄准框——永远不要相信轮廓。",
    # Chapter 7
    "AWN is moving its memory cores. If the transfer completes, everything we learned about SOVEREIGN's architecture becomes worthless.": "AWN 正在转移记忆核心。如果传输完成，我们掌握的关于主宰架构的一切情报都将一文不值。",
    "The convoy is protected by SERAPH — the network's execution layer. Its HALO weapon fills the entire battlespace.": "运输编队由「六翼天使」护卫——那是网络的执行层防御 AI。它的光环武器会填满整个战场空间。",
    "Wait for the halo to contract. That is the only moment SERAPH's spine is exposed. Strike then, or not at all.": "等待光环收缩。那是唯一能暴露六翼天使主脊的时刻。要么那时出手，要么永远别出手。",
    # Chapter 8
    "Base MERIDIAN is burning its last fusion cell to hold the uplink open. We have one shot.": "子午线基地正在燃烧最后一个聚变电池来维持上行链路。我们只有一次机会。",
    "SOVEREIGN has assumed direct control of every remaining unit in the sector. No more command layers. No more signal lag. Pure machine will.": "主宰已经接管了扇区内所有剩余单位的直接控制权。不再有指挥层级。不再有信号延迟。纯粹的机器意志。",
    "You are the last thing between AWN and total victory. WARDEN — the horizon is yours.": "你是 AWN 与全面胜利之间的最后一道屏障。守望者——地平线属于你。",
    "ORISON final transmission: It has been an honor. Uplink closing. Mission complete.": "祷言最后通讯：这是我的荣幸。上行链路关闭。任务完成。",
})

# Merge lore translations from lore.py
try:
    from .lore import collect_lore_translations
    ZH.update(collect_lore_translations())
except ImportError:
    pass


def _format_dynamic(text: str) -> str:
    patterns = (
        (r"^SCORE (\d+)$", r"得分 \1"),
        (r"^BEST (\d+)$", r"最高 \1"),
        (r"^LINES (\d+)\s+LEVEL (\d+)$", r"消行 \1　等级 \2"),
        (r"^TIME (.+)$", r"时间 \1"),
        (r"^Current: (.+)$", r"当前：\1"),
        (r"^OPEN (\d+)$", r"已翻开 \1"),
        (r"^CHAPTER (\d+)$", r"章节 \1"),
        (r"^CHAPTER (\d+) // (.+)$", r"章节 \1 // \2"),
        (r"^(.+) / MISSION$", r"\1 / 任务"),
        (r"^(.+) / BOSS$", r"\1 / Boss"),
        (r"^OBJECTIVE: DESTROY (.+)$", r"任务目标：摧毁 \1"),
        (r"^(.+) // PHASE (\d+)$", r"\1 // 阶段 \2"),
        (r"^(.+) // PHASE (\d+) // ARMOR SHIFT$", r"\1 // 阶段 \2 // 装甲切换"),
        (r"^WARNING // (.+) // PHASE (\d+)$", r"警报 // \1 // 阶段 \2"),
        (r"^ALERT: HOSTILE COMMAND FRAME (.+) CONFIRMED\.$", r"警报：确认敌方指挥机体 \1。"),
        (r"^COMMAND: CHAPTER (\d+) FLIGHT WINDOW IS OPEN\.$", r"指挥部：第 \1 章飞行窗口已开启。"),
        (r"^ARCHIVE (\d+) // (.+)$", r"档案 \1 // \2"),
        (r"^COMMAND FRAME: (.+)$", r"指挥机体：\1"),
        (r"^A / D  RECORD (\d+) / (\d+)\s+ESC  RETURN$", r"A / D：档案 \1 / \2　ESC：返回"),
        (r"^(.+)\s+ESC  MENU$", r"\1　ESC：菜单"),
        (r"^(.+)  PLAY (.+)$", r"\1　游玩时间 \2"),
        (r"^CHARGE (\d+)%$", r"充能 \1%"),
        (r"^DESTROYED (\d+) / (\d+)$", r"击破 \1 / \2"),
        (r"^GRAZES (\d+)\s+HULL (\d+) / 5$", r"擦弹 \1　耐久 \2 / 5"),
        (r"^COMBO\s+(\d+)$", r"连击 \1"),
        (r"^GRAZE\s+(\d+)$", r"擦弹 \1"),
        (r"^MULTI\s+x(.+)$", r"倍率 x\1"),
        (r"^COMPLETE (\d+) / (\d+)\s+(\d+)%$", r"完成 \1 / \2　\3%"),
        (r"^(.+) / LOCKED$", r"\1 / 未解锁"),
        (r"^UNLOCKED (\d+) / (\d+)$", r"已解锁 \1 / \2"),
        (r"^(.+) WINS$", r"\1胜利"),
        (r"^(.+)'S TURN$", r"轮到\1"),
        (r"^FPS (.+)$", r"帧率 \1"),
        (r"^INDEX (\d+)$", r"指数 \1"),
        (r"^UNLOCKED (\d+) / (\d+)$", r"已解锁 \1 / \2"),
    )
    for pattern, replacement in patterns:
        if re.match(pattern, text):
            return re.sub(pattern, replacement, text)
    return text


def translate(text: str) -> str:
    if not is_chinese() or not isinstance(text, str):
        return text
    translated = ZH.get(text)
    if translated is not None:
        return translated
    return _format_dynamic(text)


def contains_chinese(text: str) -> bool:
    return bool(re.search(r"[\u3400-\u9fff]", text))


def register_game_translations(game_id: str, translations: dict[str, str]) -> None:
    """Register translation entries for a new game.

    Args:
        game_id: Unique game identifier (e.g. "pacman")
        translations: Dict of EN key -> ZH value pairs
    """
    ZH.update(translations)
